// Question (1)
alert("Error!Please enter the valid password.") 
// Question (2)
alert("Welcome to JS land.. \nHappy coding!")
// Question (3)
alert("Happy to JS land..")
// Question (4)
alert("Happy coding! \nprevent this page from creating additional dialogs.")
// Question (5)
alert("Hello.. I can run JS through my web browser's consloe")